import { PostTypes } from "@/types/common.types";
import { SearchPosts } from "@/components";

const Home: React.FC = async () => {

    const posts = await fetchPosts(process.env.SERVER_URL!);

    return (
        <section className="max-w-7xl mx-auto">
            <div>
                <h1 className="font-extrabold text-[#222328] text-[32px]">The Community Showcase</h1>
                <p className="mt-2 text-[#666e75] text-[16px] max-w-[500px]">
                    Browse through a collection of imaginative and visually stunning images generated by DALL-E AI
                </p>
            </div>
            <SearchPosts posts={posts}/>
        </section>
    )
}

const fetchPosts = async (url: string): Promise<Array<PostTypes>> => {
    try {
        const response = await fetch(`http://localhost:3000/api/post`, {
            method: "GET",
            headers: {
                "Content-Type": "application/json"
            },
            next: {
                tags: ["collection"],
                revalidate: 60
            }
        })
        const posts = await response.json();
        return posts;
    } catch (e: any) {
        console.log(e.message);
        return [];
    }
}

export default Home;